version: 2
updates:
  - package-ecosystem: nuget
    directory: /api
    schedule:
      interval: weekly
    groups:
      dotnet-dependencies:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /apps/mobile
    schedule:
      interval: weekly
    groups:
      mobile-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /infra
    schedule:
      interval: weekly
